"""remove app market tables

Revision ID: 019f3ea7a56a
Revises: c3e59b0f4a12
Create Date: 2026-02-16 01:11:26.421507

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '019f3ea7a56a'
down_revision: Union[str, None] = 'c3e59b0f4a12'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('app_permissions')
    op.drop_table('app_reviews')
    op.drop_table('app_screenshots')
    op.drop_table('app_versions')
    op.drop_index(op.f('ix_apps_category'), table_name='apps')
    op.drop_index(op.f('ix_apps_status'), table_name='apps')
    op.drop_table('apps')
    op.drop_table('app_installs')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_installs',
    sa.Column('app_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], name=op.f('app_installs_app_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('app_installs_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('app_installs_pkey')),
    sa.UniqueConstraint('app_id', 'user_id', name=op.f('app_installs_app_id_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('apps',
    sa.Column('id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('long_description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('author_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('icon_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('entry_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('current_version', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('install_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('rating_avg', sa.NUMERIC(precision=3, scale=2), autoincrement=False, nullable=False),
    sa.Column('review_count', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('reviewer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('review_notes', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('rejection_reason', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('reviewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('apps_author_id_fkey')),
    sa.ForeignKeyConstraint(['reviewer_id'], ['users.id'], name=op.f('apps_reviewer_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('apps_pkey'))
    )
    op.create_index(op.f('ix_apps_status'), 'apps', ['status'], unique=False)
    op.create_index(op.f('ix_apps_category'), 'apps', ['category'], unique=False)
    op.create_table('app_versions',
    sa.Column('app_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('version', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('changelog', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('manifest', postgresql.JSONB(astext_type=sa.Text()), autoincrement=False, nullable=False),
    sa.Column('bundle_url', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('status', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], name=op.f('app_versions_app_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('app_versions_pkey')),
    sa.UniqueConstraint('app_id', 'version', name=op.f('app_versions_app_id_version_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('app_screenshots',
    sa.Column('app_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), autoincrement=False, nullable=False),
    sa.Column('sort_order', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], name=op.f('app_screenshots_app_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('app_screenshots_pkey'))
    )
    op.create_table('app_reviews',
    sa.Column('app_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('rating', sa.SMALLINT(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), autoincrement=False, nullable=True),
    sa.Column('comment', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.CheckConstraint('rating >= 1 AND rating <= 5', name=op.f('check_rating_range')),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], name=op.f('app_reviews_app_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('app_reviews_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('app_reviews_pkey')),
    sa.UniqueConstraint('app_id', 'user_id', name=op.f('app_reviews_app_id_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('app_permissions',
    sa.Column('app_id', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('permission', sa.VARCHAR(length=200), autoincrement=False, nullable=False),
    sa.Column('granted', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('granted_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text("'2026-02-15 22:01:26.416072+00'::timestamp with time zone"), autoincrement=False, nullable=False),
    sa.Column('revoked_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['app_id'], ['apps.id'], name=op.f('app_permissions_app_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('app_permissions_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('app_permissions_pkey')),
    sa.UniqueConstraint('app_id', 'user_id', 'permission', name=op.f('app_permissions_app_id_user_id_permission_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
