"""add user_containers and container_events tables

Revision ID: 149884c2c36d
Revises: 7d2c9f1a3b4e
Create Date: 2026-02-11 17:13:50.505743

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "149884c2c36d"
down_revision: str | None = "7d2c9f1a3b4e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "container_events",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.String(length=50), nullable=False),
        sa.Column("details", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_container_events_user_id"), "container_events", ["user_id"], unique=False
    )
    op.create_table(
        "user_containers",
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("container_id", sa.String(length=100), nullable=True),
        sa.Column("container_name", sa.String(length=200), nullable=False),
        sa.Column("container_ip", sa.String(length=45), nullable=True),
        sa.Column("status", sa.String(length=20), nullable=False),
        sa.Column("cpu_limit", sa.BigInteger(), nullable=False),
        sa.Column("ram_limit", sa.BigInteger(), nullable=False),
        sa.Column("disk_limit", sa.BigInteger(), nullable=False),
        sa.Column("network_rate", sa.String(length=20), nullable=False),
        sa.Column("last_activity", sa.DateTime(timezone=True), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("container_name"),
    )
    op.create_index(op.f("ix_user_containers_user_id"), "user_containers", ["user_id"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_user_containers_user_id"), table_name="user_containers")
    op.drop_table("user_containers")
    op.drop_index(op.f("ix_container_events_user_id"), table_name="container_events")
    op.drop_table("container_events")
    # ### end Alembic commands ###
