"""add file_system_nodes table

Revision ID: 6c4e0cbc0a5b
Revises: 149884c2c36d
Create Date: 2026-02-11 18:02:39.351466

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6c4e0cbc0a5b'
down_revision: Union[str, None] = '149884c2c36d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('file_system_nodes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('path', sa.String(length=4096), nullable=False),
    sa.Column('node_type', sa.String(length=20), nullable=False),
    sa.Column('mime_type', sa.String(length=255), nullable=True),
    sa.Column('size', sa.BigInteger(), server_default='0', nullable=False),
    sa.Column('is_trashed', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('original_path', sa.String(length=4096), nullable=True),
    sa.Column('trashed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('content_ref', sa.String(length=500), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("node_type IN ('file', 'directory')", name='ck_node_type'),
    sa.ForeignKeyConstraint(['parent_id'], ['file_system_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'path', name='uq_user_path')
    )
    op.create_index('ix_user_parent', 'file_system_nodes', ['user_id', 'parent_id'], unique=False)
    op.create_index('ix_user_trashed', 'file_system_nodes', ['user_id', 'is_trashed'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_user_trashed', table_name='file_system_nodes')
    op.drop_index('ix_user_parent', table_name='file_system_nodes')
    op.drop_table('file_system_nodes')
    # ### end Alembic commands ###
