"""add port_forwards table

Revision ID: 9eb274f79236
Revises: 15bbf44cfc76
Create Date: 2026-02-28 22:24:54.159936

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9eb274f79236'
down_revision: Union[str, None] = '15bbf44cfc76'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('port_forwards',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subdomain', sa.String(length=63), nullable=False),
    sa.Column('container_port', sa.Integer(), nullable=False),
    sa.Column('container_ip', sa.String(length=45), nullable=True),
    sa.Column('protocol', sa.String(length=10), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'container_port', name='uq_user_container_port')
    )
    op.create_index(op.f('ix_port_forwards_subdomain'), 'port_forwards', ['subdomain'], unique=True)
    op.create_index(op.f('ix_port_forwards_user_id'), 'port_forwards', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_port_forwards_user_id'), table_name='port_forwards')
    op.drop_index(op.f('ix_port_forwards_subdomain'), table_name='port_forwards')
    op.drop_table('port_forwards')
    # ### end Alembic commands ###
