"""add desktop position columns

Revision ID: b986fbf76c4a
Revises: 6c4e0cbc0a5b
Create Date: 2026-02-11 23:43:40.522123

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b986fbf76c4a"
down_revision: str | None = "6c4e0cbc0a5b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("file_system_nodes", sa.Column("desktop_x", sa.Integer(), nullable=True))
    op.add_column("file_system_nodes", sa.Column("desktop_y", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("file_system_nodes", "desktop_y")
    op.drop_column("file_system_nodes", "desktop_x")
    # ### end Alembic commands ###
