"""add is_system to apps

Revision ID: d6d74a6fd001
Revises: d4a7e2b8c915
Create Date: 2026-02-16 22:43:19.556100

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6d74a6fd001'
down_revision: Union[str, None] = 'd4a7e2b8c915'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('apps', sa.Column('is_system', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('apps', 'is_system')
    # ### end Alembic commands ###
